openapi: 3.1.0
info:
  title: Example API
  version: 1.0.0
paths: {}
components:
  schemas:

    Envelope:
      type: object
      description: Top-level container holding the message header and body.
      properties:
        Header:
          $ref: '#/components/schemas/Header'
          description: Original name: (not specified). metadata
          example: {}
        Body:
          $ref: '#/components/schemas/Body'
          description: Original name: (not specified). Message body with arrival and departure records
          example: {}
      required: [Header, Body]

    Header:
      type: object
      properties:
        SentDateTime:
          type: string
          format: date-time
          description: Original name: (not specified). timestamp when this message was sent
          example: "2025-04-29T06:50:50.00000Z"
        SequenceNumber:
          type: [number, "null"]
          description: Original name: (not specified). Incremental sequence identifier for the message. For full load is null and can be omitted
          example: null
        MessageType:
          type: string
          description: Original name: (not specified). Payload message type
          enum: [FullLoad, Update]
          example: FullLoad
      required: [SentDateTime, MessageType]

    Body:
      type: object
      properties:
        Arrivals:
          type: array
          description: Original name: (not specified). array (can hold multiple records)
          items:
            $ref: '#/components/schemas/Arrival'
          example: [{}]
        Departures:
          type: array
          description: Original name: (not specified). array (can hold multiple records)
          items:
            $ref: '#/components/schemas/Departure'
          example: [{}]
      required: [Arrivals, Departures]

    Arrival:
      type: object
      properties:
        Operation:
          type: string
          description: Original name: (not specified). operation type: insert, update
          enum: [insert, update, delete]
          example: insert
        FlightLegRepeatSequence:
          type: number
          description: Original name: FLR. Flight leg repeat sequence number
          example: 0
        FlightDesignator:
          type: string
          description: Original name: FLT. IATA flight designator
          example: LX087
        ScheduledDate:
          type: string
          format: date
          description: Original name: SDT. Scheduled arrival date in ZRH (YYYY-MM-DD)
          example: "2025-04-29"
        CancellationFlag:
          type: [string, "null"]
          description: Original name: CAN. Cancellation flag (null if not cancelled)
          example: null
        SchengenIndicator:
          type: string
          description: Original name: SCH. Schengen area indicator
          enum: [Y, N]
          example: Y
        FlightType:
          type: number
          description: Original name: CAT. Flugkategorie → FLIRT Flighttype
          example: 10
        Aircraft:
          $ref: '#/components/schemas/Aircraft'
          description: Original name: (not specified). Aircraft
          example: {}
        LinksAndShares:
          $ref: '#/components/schemas/LinksAndShares'
          description: Original name: (not specified). LinksAndShares
          example: {}
        Times:
          $ref: '#/components/schemas/Times'
          description: Original name: (not specified). Times
          example: {}
        Route:
          $ref: '#/components/schemas/Route'
          description: Original name: (not specified). Route
          example: {}
        Load:
          $ref: '#/components/schemas/Load'
          description: Original name: (not specified). Load
          example: {}
        Airport:
          $ref: '#/components/schemas/Airport'
          description: Original name: (not specified). Airport
          example: {}
        Delays:
          $ref: '#/components/schemas/Delays'
          description: Original name: (not specified). Delays
          example: {}
      required:
        [Operation, FlightLegRepeatSequence, FlightDesignator, ScheduledDate]

    Aircraft:
      type: object
      properties:
        SeatCapacity:
          type: number
          description: Original name: CAP. Total seat capacity
          example: 236
        AircraftRegistration:
          type: string
          description: Original name: REG. Aircraft registration code
          example: HBJHE
        IcaoAircraftModel:
          type: string
          description: Original name: ICT. Aircraft model type code (ICAO)
          example: A330
        IataAircraftModel:
          type: string
          description: Original name: TYP. Aircraft model type code (IATA)
          example: "330"
        AircraftSubtype:
          type: string
          description: Original name: TYS. Specific aircraft subtype code
          example: "333"
        NoiseCertificationLevel:
          type: [string, "null"]
          description: Original name: NCL. Noise certification level
          example: null

    LinksAndShares:
      type: object
      properties:
        LinkedFlightRepeatSequence:
          type: number
          description: Original name: LKR. Linked flight repeat sequence number
          example: 0
        LinkedFlightDesignator:
          type: string
          description: Original name: LKF. Linked flight IATA code
          example: LX252
        LinkedFlightDate:
          type: string
          format: date
          description: Original name: LKS. Linked flight scheduled date (YYYY-MM-DD)
          example: "2025-04-29"
        CodeshareFlights:
          type: array
          description: Original name: CSF. Codeshare flight list (Airline + flightnumber) array
          items:
            type: string
          example: ["AC 6820"]
        MasterFlightNumber:
          type: [string, "null"]
          description: Original name: MFF. Master flight number (if codeshared)
          example: null
        CodeshareStatus:
          type: string
          description: Original name: SST. Codeshare status (count or 'SF' for shared)
          example: "01"

    Times:
      type: object
      properties:
        OriginScheduledTime:
          type: string
          format: date-time
          description: Original name: STP. Scheduled departure time from Origin
          example: "2025-04-28T21:25:00Z"
        ScheduledArrivalTime:
          type: string
          format: date-time
          description: Original name: STA. Scheduled Time of Arrival time in ZRH
          example: "2025-04-29T04:10:00Z"
        TouchDownTime:
          type: string
          format: date-time
          description: Original name: TDT. TouchDown time
          example: "2025-04-29T04:08:36Z"
        ActualArrivalTime:
          type: string
          format: date-time
          description: Original name: ATA. Actual Time of Arrival (On-Block)
          example: "2025-04-29T04:15:07Z"
        EstimatedArrivalTime:
          type: string
          format: date-time
          description: Original name: ETA. Estimated arrival time
          example: "2025-04-29T04:14:00Z"

    Route:
      type: object
      properties:
        OriginAirportIATA:
          type: string
          description: Original name: ORG. Origin airport IATA code
          example: YUL
        OriginAirportICAO:
          type: string
          description: Original name: IOR. Origin airport ICAO code
          example: CYUL
        ViaStopIATA3:
          type: [string, "null"]
          description: Original name: PV3. AOS catalog: Third via location IATA Code (only IATA available)
          example: null
        ViaStopIATA2:
          type: [string, "null"]
          description: Original name: PV2. AOS catalog: Second via location IATA Code
          example: null
        PreviousStopIATA:
          type: string
          description: Original name: PV1. AOS catalog: First via location IATA Code (ViaStopIATA1)
          example: YUL
        PreviousStopICAO:
          type: string
          description: Original name: ILL. Previous (closest to ZRH) stop ICAO code. AOS catalog: ICAO location for last landing
          example: CYUL

    Load:
      type: object
      properties:
        PassengerCount:
          type: number
          description: Original name: PAX. Total number of passengers
          example: 229
        ConnectingBaggageCount:
          type: number
          description: Original name: PCB. Total connecting baggage pieces
          example: 158
        ConnectingPassengerCount:
          type: number
          description: Original name: PX5. Total connecting passengers
          example: 178
        LocalPassengerCount:
          type: number
          description: Original name: PXL. Total local passengers
          example: 51
        TransitPassengerCount:
          type: [number, "null"]
          description: Original name: PXT. Total transit passengers
          example: null
        CargoWeightLoaded:
          type: number
          description: Original name: CGD. Local cargo/freight weight in kg (New field)
          example: 0
        TransitCargoWeight:
          type: number
          description: Original name: CGF. Transit cargo/freight weight in kg (New field)
          example: 0
        LocalCargoWeight:
          type: number
          description: Original name: CGL. Local cargo/freight weight in kg (New field)
          example: 0

Airport:
  type: object
  properties:
    City:
      type: string
      description: Original name: CTY. Origin city name
      example: Montreal
    Gate:
      type: string
      description: Original name: GAT. Assigned arrival gate
      example: E46
    GateExtraInformation:
      type: string
      description: Original name: GTX. Gate extra information
      example: B
    HandlingAgent:
      type: string
      description: Original name: HDL. Ground handling agent code
      example: SWP
    Runway:
      type: string
      description: Original name: RWY. Arrival runway identifier
      example: "34"
    ParkingStand:
      type: string
      description: Original name: TAR. Assigned parking stand/position
      example: E46
    Terminal:
      type: string
      description: Original name: TER. Arrival terminal number
      example: "2"

Delays:
  type: object
  properties:
    IrregularityCode1:
      type: [string, "null"]
      description: Original name: IR1. Irregularity reason codes
    IrregularityCode2:
      type: [string, "null"]
      description: Original name: IR2. Irregularity reason codes
    IrregularityCode3:
      type: [string, "null"]
      description: Original name: IR3. Irregularity reason codes
    IrregularityCode4:
      type: [string, "null"]
      description: Original name: IR4. Irregularity reason codes
    DelayDuration1:
      type: [number, "null"]
      description: Original name: DL1. Delay durations in minutes for each code
    DelayDuration2:
      type: [number, "null"]
      description: Original name: DL2. Delay durations in minutes for each code
    DelayDuration3:
      type: [number, "null"]
      description: Original name: DL3. Delay durations in minutes for each code
    DelayDuration4:
      type: [number, "null"]
      description: Original name: DL4. Delay durations in minutes for each code

    Departure:
      type: object
      description: Departure object (definition pending)
